import { City, Market, Product, User, PriceSubmission, Badge } from '@/types';

// Mock Cities - Comprehensive list of Moroccan cities with traditional souks
export const mockCities: City[] = [
  // Tanger-Tétouan-Al Hoceima Region
  {
    id: '1',
    name: 'Tangier',
    nameAr: 'طنجة',
    nameFr: 'Tanger',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.7595, lng: -5.8340 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Tétouan',
    nameAr: 'تطوان',
    nameFr: 'Tétouan',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.5785, lng: -5.3684 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Al Hoceima',
    nameAr: 'الحسيمة',
    nameFr: 'Al Hoceima',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.2517, lng: -3.9317 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Asilah',
    nameAr: 'أصيلة',
    nameFr: 'Asilah',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.4650, lng: -6.0350 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Chefchaouen',
    nameAr: 'شفشاون',
    nameFr: 'Chefchaouen',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.1714, lng: -5.2636 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Fnideq',
    nameAr: 'الفنيدق',
    nameFr: 'Fnideq',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.8500, lng: -5.3580 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    name: 'Ksar El Kebir',
    nameAr: 'القصر الكبير',
    nameFr: 'Ksar El Kebir',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.0018, lng: -5.9045 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '8',
    name: 'Larache',
    nameAr: 'العرائش',
    nameFr: 'Larache',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.1932, lng: -6.1563 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    name: 'M\'diq',
    nameAr: 'مضيق',
    nameFr: 'M\'diq',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.6850, lng: -5.3260 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    name: 'Martil',
    nameAr: 'مارتيل',
    nameFr: 'Martil',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 35.6170, lng: -5.2750 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '11',
    name: 'Ouazzane',
    nameAr: 'وزان',
    nameFr: 'Ouazzane',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 34.7973, lng: -5.5835 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    name: 'Taounate',
    nameAr: 'تاونات',
    nameFr: 'Taounate',
    region: 'Tanger-Tétouan-Al Hoceima',
    coordinates: { lat: 34.5317, lng: -4.6372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // L'Oriental Region
  {
    id: '13',
    name: 'Oujda',
    nameAr: 'وجدة',
    nameFr: 'Oujda',
    region: 'L\'Oriental',
    coordinates: { lat: 34.6814, lng: -1.9086 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '14',
    name: 'Nador',
    nameAr: 'الناظور',
    nameFr: 'Nador',
    region: 'L\'Oriental',
    coordinates: { lat: 35.1740, lng: -2.9287 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '15',
    name: 'Berkane',
    nameAr: 'بركان',
    nameFr: 'Berkane',
    region: 'L\'Oriental',
    coordinates: { lat: 34.9218, lng: -2.3184 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '16',
    name: 'Taourirt',
    nameAr: 'تاوريرت',
    nameFr: 'Taourirt',
    region: 'L\'Oriental',
    coordinates: { lat: 34.4096, lng: -2.8934 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '17',
    name: 'Guercif',
    nameAr: 'كرسيف',
    nameFr: 'Guercif',
    region: 'L\'Oriental',
    coordinates: { lat: 34.2268, lng: -3.3512 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '18',
    name: 'Beni Ansar',
    nameAr: 'بني انصار',
    nameFr: 'Beni Ansar',
    region: 'L\'Oriental',
    coordinates: { lat: 35.1689, lng: -2.9280 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '19',
    name: 'Ahfir',
    nameAr: 'أحفير',
    nameFr: 'Ahfir',
    region: 'L\'Oriental',
    coordinates: { lat: 34.9420, lng: -2.1830 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '20',
    name: 'Driouch',
    nameAr: 'الدريوش',
    nameFr: 'Driouch',
    region: 'L\'Oriental',
    coordinates: { lat: 35.1374, lng: -3.3891 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '21',
    name: 'Selouane',
    nameAr: 'سلوان',
    nameFr: 'Selouane',
    region: 'L\'Oriental',
    coordinates: { lat: 35.0847, lng: -2.9438 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '22',
    name: 'Zaio',
    nameAr: 'زايو',
    nameFr: 'Zaio',
    region: 'L\'Oriental',
    coordinates: { lat: 35.0161, lng: -2.7394 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '23',
    name: 'Saidia',
    nameAr: 'السعيدية',
    nameFr: 'Saidia',
    region: 'L\'Oriental',
    coordinates: { lat: 35.0939, lng: -2.2278 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Fès-Meknès Region
  {
    id: '24',
    name: 'Fez',
    nameAr: 'فاس',
    nameFr: 'Fès',
    region: 'Fès-Meknès',
    coordinates: { lat: 34.0181, lng: -5.0078 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '25',
    name: 'Meknès',
    nameAr: 'مكناس',
    nameFr: 'Meknès',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.8935, lng: -5.5473 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '26',
    name: 'Sefrou',
    nameAr: 'صفرو',
    nameFr: 'Sefrou',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.8307, lng: -4.8372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '27',
    name: 'Taza',
    nameAr: 'تازة',
    nameFr: 'Taza',
    region: 'Fès-Meknès',
    coordinates: { lat: 34.2133, lng: -4.0103 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '28',
    name: 'Ifrane',
    nameAr: 'إفران',
    nameFr: 'Ifrane',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.5228, lng: -5.1100 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '29',
    name: 'Azrou',
    nameAr: 'أزرو',
    nameFr: 'Azrou',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.4347, lng: -5.2214 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '30',
    name: 'Moulay Yacoub',
    nameAr: 'مولاي يعقوب',
    nameFr: 'Moulay Yacoub',
    region: 'Fès-Meknès',
    coordinates: { lat: 34.0847, lng: -5.1761 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '31',
    name: 'Tifelt',
    nameAr: 'تيفلت',
    nameFr: 'Tifelt',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.8986, lng: -6.3164 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Rabat-Salé-Kénitra Region
  {
    id: '32',
    name: 'Rabat',
    nameAr: 'الرباط',
    nameFr: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.0209, lng: -6.8416 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '33',
    name: 'Salé',
    nameAr: 'سلا',
    nameFr: 'Salé',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.0531, lng: -6.7985 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '34',
    name: 'Kénitra',
    nameAr: 'القنيطرة',
    nameFr: 'Kénitra',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2610, lng: -6.5802 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '35',
    name: 'Temara',
    nameAr: 'تمارة',
    nameFr: 'Temara',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.9287, lng: -6.9067 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '36',
    name: 'Skhirat',
    nameAr: 'الصخيرات',
    nameFr: 'Skhirat',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.8539, lng: -7.0364 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '37',
    name: 'Khemisset',
    nameAr: 'الخميسات',
    nameFr: 'Khemisset',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.8244, lng: -6.0669 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '38',
    name: 'Sidi Kacem',
    nameAr: 'سيدي قاسم',
    nameFr: 'Sidi Kacem',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2214, lng: -5.7081 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '39',
    name: 'Sidi Slimane',
    nameAr: 'سيدي سليمان',
    nameFr: 'Sidi Slimane',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2656, lng: -5.9267 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Beni Mellal-Khénifra Region
  {
    id: '40',
    name: 'Beni Mellal',
    nameAr: 'بني ملال',
    nameFr: 'Beni Mellal',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 32.3372, lng: -6.3498 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '41',
    name: 'Khenifra',
    nameAr: 'خنيفرة',
    nameFr: 'Khenifra',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 32.9356, lng: -5.6681 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '42',
    name: 'Azilal',
    nameAr: 'أزيلال',
    nameFr: 'Azilal',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 31.9647, lng: -6.5711 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '43',
    name: 'Fquih Ben Salah',
    nameAr: 'الفقيه بن صالح',
    nameFr: 'Fquih Ben Salah',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 32.5019, lng: -6.6889 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '44',
    name: 'Kasba Tadla',
    nameAr: 'قصبة تادلة',
    nameFr: 'Kasba Tadla',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 32.5936, lng: -6.2661 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '45',
    name: 'Midelt',
    nameAr: 'ميدلت',
    nameFr: 'Midelt',
    region: 'Beni Mellal-Khénifra',
    coordinates: { lat: 32.6792, lng: -4.7339 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Casablanca-Settat Region
  {
    id: '46',
    name: 'Casablanca',
    nameAr: 'الدار البيضاء',
    nameFr: 'Casablanca',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '47',
    name: 'Mohammedia',
    nameAr: 'المحمدية',
    nameFr: 'Mohammedia',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6866, lng: -7.3833 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '48',
    name: 'El Jadida',
    nameAr: 'الجديدة',
    nameFr: 'El Jadida',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2316, lng: -8.5007 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '49',
    name: 'Settat',
    nameAr: 'سطات',
    nameFr: 'Settat',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.0014, lng: -7.6164 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '50',
    name: 'Berrechid',
    nameAr: 'برشيد',
    nameFr: 'Berrechid',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2650, lng: -7.5839 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '51',
    name: 'Benslimane',
    nameAr: 'بن سليمان',
    nameFr: 'Benslimane',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6144, lng: -7.1250 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '52',
    name: 'Khouribga',
    nameAr: 'خريبكة',
    nameFr: 'Khouribga',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.8811, lng: -6.9063 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '53',
    name: 'Oued Zem',
    nameAr: 'وادي زم',
    nameFr: 'Oued Zem',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.8656, lng: -6.5728 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '54',
    name: 'Azemmour',
    nameAr: 'أزمور',
    nameFr: 'Azemmour',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2847, lng: -8.3411 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '55',
    name: 'Sidi Bennour',
    nameAr: 'سيدي بنور',
    nameFr: 'Sidi Bennour',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.6550, lng: -8.4281 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '56',
    name: 'Youssoufia',
    nameAr: 'اليوسفية',
    nameFr: 'Youssoufia',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.2458, lng: -8.5297 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '57',
    name: 'Ben Guerir',
    nameAr: 'بن جرير',
    nameFr: 'Ben Guerir',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.2364, lng: -7.9511 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Marrakech-Safi Region
  {
    id: '58',
    name: 'Marrakech',
    nameAr: 'مراكش',
    nameFr: 'Marrakech',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '59',
    name: 'Safi',
    nameAr: 'آسفي',
    nameFr: 'Safi',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.2994, lng: -9.2372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '60',
    name: 'Essaouira',
    nameAr: 'الصويرة',
    nameFr: 'Essaouira',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.5085, lng: -9.7595 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '61',
    name: 'El Kelaa Des Sraghna',
    nameAr: 'قلعة السراغنة',
    nameFr: 'El Kelaa Des Sraghna',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.0556, lng: -7.4056 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '62',
    name: 'Amizmiz',
    nameAr: 'أميزميز',
    nameFr: 'Amizmiz',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.2097, lng: -8.2392 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '63',
    name: 'Asni',
    nameAr: 'أسني',
    nameFr: 'Asni',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.2386, lng: -7.9739 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '64',
    name: 'Imlil',
    nameAr: 'إمليل',
    nameFr: 'Imlil',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.1356, lng: -7.9250 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '65',
    name: 'Ourika',
    nameAr: 'أوريكة',
    nameFr: 'Ourika',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.3986, lng: -7.8689 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '66',
    name: 'Tahanaout',
    nameAr: 'تحناوت',
    nameFr: 'Tahanaout',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.4842, lng: -8.0286 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Drâa-Tafilalet Region
  {
    id: '67',
    name: 'Ouarzazate',
    nameAr: 'ورزازات',
    nameFr: 'Ouarzazate',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 30.9335, lng: -6.9370 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '68',
    name: 'Errachidia',
    nameAr: 'الراشيدية',
    nameFr: 'Errachidia',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.9314, lng: -4.4239 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '69',
    name: 'Zagora',
    nameAr: 'زاكورة',
    nameFr: 'Zagora',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 30.3314, lng: -5.8372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '70',
    name: 'Tinghir',
    nameAr: 'تنغير',
    nameFr: 'Tinghir',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.5147, lng: -5.5347 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '71',
    name: 'Rissani',
    nameAr: 'الريصاني',
    nameFr: 'Rissani',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.2867, lng: -4.2539 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '72',
    name: 'Erfoud',
    nameAr: 'أرفود',
    nameFr: 'Erfoud',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.4347, lng: -4.2381 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '73',
    name: 'Merzouga',
    nameAr: 'مرزوقة',
    nameFr: 'Merzouga',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.0939, lng: -4.0147 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '74',
    name: 'Boumalne Dades',
    nameAr: 'بومالن دادس',
    nameFr: 'Boumalne Dades',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.2831, lng: -5.9700 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '75',
    name: 'Skoura',
    nameAr: 'سكورة',
    nameFr: 'Skoura',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.0581, lng: -6.5614 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '76',
    name: 'Kelaat M\'Gouna',
    nameAr: 'قلعة مڭونة',
    nameFr: 'Kelaat M\'Gouna',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.2481, lng: -6.1889 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '77',
    name: 'Goulmima',
    nameAr: 'كلميمة',
    nameFr: 'Goulmima',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.6486, lng: -4.6872 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Souss-Massa Region
  {
    id: '78',
    name: 'Agadir',
    nameAr: 'أڭادير',
    nameFr: 'Agadir',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4278, lng: -9.5981 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '79',
    name: 'Inezgane',
    nameAr: 'إنزكان',
    nameFr: 'Inezgane',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3556, lng: -9.5369 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '80',
    name: 'Ait Melloul',
    nameAr: 'أيت ملول',
    nameFr: 'Ait Melloul',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3386, lng: -9.4997 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '81',
    name: 'Taroudant',
    nameAr: 'تارودانت',
    nameFr: 'Taroudant',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4731, lng: -8.8778 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '82',
    name: 'Tiznit',
    nameAr: 'تزنيت',
    nameFr: 'Tiznit',
    region: 'Souss-Massa',
    coordinates: { lat: 29.6978, lng: -9.7328 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '83',
    name: 'Tafraout',
    nameAr: 'تافراوت',
    nameFr: 'Tafraout',
    region: 'Souss-Massa',
    coordinates: { lat: 29.7267, lng: -8.9739 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '84',
    name: 'Sidi Ifni',
    nameAr: 'سيدي إفني',
    nameFr: 'Sidi Ifni',
    region: 'Souss-Massa',
    coordinates: { lat: 29.3797, lng: -10.1731 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '85',
    name: 'Mirleft',
    nameAr: 'ميرلفت',
    nameFr: 'Mirleft',
    region: 'Souss-Massa',
    coordinates: { lat: 29.5831, lng: -10.0339 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '86',
    name: 'Oulad Teima',
    nameAr: 'أولاد تايمة',
    nameFr: 'Oulad Teima',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3947, lng: -9.2156 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '87',
    name: 'Aourir',
    nameAr: 'أوريڭ',
    nameFr: 'Aourir',
    region: 'Souss-Massa',
    coordinates: { lat: 30.5231, lng: -9.6253 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '88',
    name: 'Tamraght',
    nameAr: 'تمراغت',
    nameFr: 'Tamraght',
    region: 'Souss-Massa',
    coordinates: { lat: 30.5439, lng: -9.6722 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Guelmim-Oued Noun Region
  {
    id: '89',
    name: 'Guelmim',
    nameAr: 'كلميم',
    nameFr: 'Guelmim',
    region: 'Guelmim-Oued Noun',
    coordinates: { lat: 28.9870, lng: -10.0574 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '90',
    name: 'Tan-Tan',
    nameAr: 'طانطان',
    nameFr: 'Tan-Tan',
    region: 'Guelmim-Oued Noun',
    coordinates: { lat: 28.4378, lng: -11.1031 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '91',
    name: 'Sidi Ouarzeg',
    nameAr: 'سيدي ورزگ',
    nameFr: 'Sidi Ouarzeg',
    region: 'Guelmim-Oued Noun',
    coordinates: { lat: 28.8550, lng: -10.2750 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Laâyoune-Sakia El Hamra Region
  {
    id: '92',
    name: 'Laâyoune',
    nameAr: 'العيون',
    nameFr: 'Laâyoune',
    region: 'Laâyoune-Sakia El Hamra',
    coordinates: { lat: 27.1536, lng: -13.1994 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Dakhla-Oued Ed-Dahab Region
  {
    id: '93',
    name: 'Dakhla',
    nameAr: 'الداخلة',
    nameFr: 'Dakhla',
    region: 'Dakhla-Oued Ed-Dahab',
    coordinates: { lat: 23.7181, lng: -15.9581 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '21',
    name: 'Ouislane',
    nameAr: 'Ouislane',
    nameFr: 'Ouislane',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.8200, lng: -5.5100 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '21',
    name: 'Azrou',
    nameAr: 'Azrou',
    nameFr: 'Azrou',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.4343, lng: -5.2229 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '22',
    name: 'Ain Chkef',
    nameAr: 'Ain Chkef',
    nameFr: 'Ain Chkef',
    region: 'Fès-Meknès',
    coordinates: { lat: 34.0400, lng: -5.0200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '23',
    name: 'Sefrou',
    nameAr: 'Sefrou',
    nameFr: 'Sefrou',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.8315, lng: -4.8372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '24',
    name: 'Taza',
    nameAr: 'Taza',
    nameFr: 'Taza',
    region: 'Fès-Meknès',
    coordinates: { lat: 34.2133, lng: -4.0100 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '25',
    name: 'Ifrane',
    nameAr: 'Ifrane',
    nameFr: 'Ifrane',
    region: 'Fès-Meknès',
    coordinates: { lat: 33.5228, lng: -5.1106 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Rabat-Salé-Kénitra
  {
    id: '26',
    name: 'Rabat',
    nameAr: 'Rabat',
    nameFr: 'Rabat',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.0209, lng: -6.8416 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '27',
    name: 'Salé',
    nameAr: 'Salé',
    nameFr: 'Salé',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.0531, lng: -6.7985 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '28',
    name: 'Ameur',
    nameAr: 'Ameur',
    nameFr: 'Ameur',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.0150, lng: -6.8500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '29',
    name: 'Témara',
    nameAr: 'Témara',
    nameFr: 'Témara',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.9287, lng: -6.9063 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '30',
    name: 'Skhirat',
    nameAr: 'Skhirat',
    nameFr: 'Skhirat',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.8548, lng: -7.0345 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '31',
    name: 'Ain El Aouda',
    nameAr: 'Ain El Aouda',
    nameFr: 'Ain El Aouda',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.9800, lng: -6.8200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '32',
    name: 'Ain Attig',
    nameAr: 'Ain Attig',
    nameFr: 'Ain Attig',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.9700, lng: -6.7800 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '33',
    name: 'Sidi Yahya Zaer',
    nameAr: 'Sidi Yahya Zaer',
    nameFr: 'Sidi Yahya Zaer',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.9200, lng: -6.7500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '34',
    name: 'Kénitra',
    nameAr: 'Kénitra',
    nameFr: 'Kénitra',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2610, lng: -6.5802 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '35',
    name: 'Souk El Arbaa',
    nameAr: 'Souk El Arbaa',
    nameFr: 'Souk El Arbaa',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.6920, lng: -6.2050 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '36',
    name: 'Mehdya',
    nameAr: 'Mehdya',
    nameFr: 'Mehdya',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2500, lng: -6.6500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '37',
    name: 'Sidi Taibi',
    nameAr: 'Sidi Taibi',
    nameFr: 'Sidi Taibi',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2800, lng: -6.6200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '38',
    name: 'Ben Mansour',
    nameAr: 'Ben Mansour',
    nameFr: 'Ben Mansour',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2200, lng: -6.5500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '39',
    name: 'Sidi Mohamed Lahmar',
    nameAr: 'Sidi Mohamed Lahmar',
    nameFr: 'Sidi Mohamed Lahmar',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2000, lng: -6.6800 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '40',
    name: 'Khémisset',
    nameAr: 'Khémisset',
    nameFr: 'Khémisset',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.8244, lng: -6.0661 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '41',
    name: 'Tiflet',
    nameAr: 'Tiflet',
    nameFr: 'Tiflet',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 33.8985, lng: -6.3236 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '42',
    name: 'Sidi Kacem',
    nameAr: 'Sidi Kacem',
    nameFr: 'Sidi Kacem',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2214, lng: -5.7081 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '43',
    name: 'Sidi Slimane',
    nameAr: 'Sidi Slimane',
    nameFr: 'Sidi Slimane',
    region: 'Rabat-Salé-Kénitra',
    coordinates: { lat: 34.2639, lng: -5.9267 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Béni Mellal-Khénifra
  {
    id: '44',
    name: 'Béni Mellal',
    nameAr: 'Béni Mellal',
    nameFr: 'Béni Mellal',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.3373, lng: -6.3498 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '45',
    name: 'Fquih Ben Salah',
    nameAr: 'Fquih Ben Salah',
    nameFr: 'Fquih Ben Salah',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.5020, lng: -6.6936 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '46',
    name: 'Souk Sebt Ouled Nemma',
    nameAr: 'Souk Sebt Ouled Nemma',
    nameFr: 'Souk Sebt Ouled Nemma',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.4500, lng: -6.5000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '47',
    name: 'Khenifra',
    nameAr: 'Khenifra',
    nameFr: 'Khenifra',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.9359, lng: -5.6675 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '48',
    name: 'Khouribga',
    nameAr: 'Khouribga',
    nameFr: 'Khouribga',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.8811, lng: -6.9063 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '49',
    name: 'Oued Zem',
    nameAr: 'Oued Zem',
    nameFr: 'Oued Zem',
    region: 'Béni Mellal-Khénifra',
    coordinates: { lat: 32.8800, lng: -6.5760 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Casablanca-Settat
  {
    id: '50',
    name: 'Casablanca',
    nameAr: 'Casablanca',
    nameFr: 'Casablanca',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '51',
    name: 'Mohammadia',
    nameAr: 'Mohammadia',
    nameFr: 'Mohammadia',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6860, lng: -7.3737 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '52',
    name: 'Ain Harrouda',
    nameAr: 'Ain Harrouda',
    nameFr: 'Ain Harrouda',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6380, lng: -7.4720 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '53',
    name: 'Bni Yakhlef',
    nameAr: 'Bni Yakhlef',
    nameFr: 'Bni Yakhlef',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6200, lng: -7.5100 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '54',
    name: 'Ech-challalate',
    nameAr: 'Ech-challalate',
    nameFr: 'Ech-challalate',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5500, lng: -7.6200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '55',
    name: 'El Jadida',
    nameAr: 'El Jadida',
    nameFr: 'El Jadida',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2316, lng: -8.5007 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '56',
    name: 'My Abdellah',
    nameAr: 'My Abdellah',
    nameFr: 'My Abdellah',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2000, lng: -8.4500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '57',
    name: 'Bouskoura',
    nameAr: 'Bouskoura',
    nameFr: 'Bouskoura',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.4564, lng: -7.6531 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '58',
    name: 'Dar Bouazza',
    nameAr: 'Dar Bouazza',
    nameFr: 'Dar Bouazza',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5239, lng: -7.7769 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '59',
    name: 'Oulad Azzouz',
    nameAr: 'Oulad Azzouz',
    nameFr: 'Oulad Azzouz',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.4800, lng: -7.7200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '60',
    name: 'Ouled Salah',
    nameAr: 'Ouled Salah',
    nameFr: 'Ouled Salah',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.4500, lng: -7.5800 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '61',
    name: 'Tit Mellil',
    nameAr: 'Tit Mellil',
    nameFr: 'Tit Mellil',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5774, lng: -7.4020 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '62',
    name: 'Lahraouyine',
    nameAr: 'Lahraouyine',
    nameFr: 'Lahraouyine',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5400, lng: -7.5400 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '63',
    name: 'Sidi Hajjaj Oued Hassar',
    nameAr: 'Sidi Hajjaj Oued Hassar',
    nameFr: 'Sidi Hajjaj Oued Hassar',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5200, lng: -7.6000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '64',
    name: 'Al Majjatia Oulad Taleb',
    nameAr: 'Al Majjatia Oulad Taleb',
    nameFr: 'Al Majjatia Oulad Taleb',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.5000, lng: -7.6500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '65',
    name: 'Benslimane',
    nameAr: 'Benslimane',
    nameFr: 'Benslimane',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.6130, lng: -7.1240 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '66',
    name: 'Bouznika',
    nameAr: 'Bouznika',
    nameFr: 'Bouznika',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.7890, lng: -7.1610 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '67',
    name: 'Berrechid',
    nameAr: 'Berrechid',
    nameFr: 'Berrechid',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2650, lng: -7.5833 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '68',
    name: 'Had Soualem',
    nameAr: 'Had Soualem',
    nameFr: 'Had Soualem',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.3200, lng: -7.5000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '69',
    name: 'Deroua',
    nameAr: 'Deroua',
    nameFr: 'Deroua',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.2300, lng: -7.4500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '70',
    name: 'Settat',
    nameAr: 'Settat',
    nameFr: 'Settat',
    region: 'Casablanca-Settat',
    coordinates: { lat: 33.0013, lng: -7.6217 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '71',
    name: 'Sidi Bennour',
    nameAr: 'Sidi Bennour',
    nameFr: 'Sidi Bennour',
    region: 'Casablanca-Settat',
    coordinates: { lat: 32.6542, lng: -8.4288 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Marrakech-Safi
  {
    id: '72',
    name: 'Marrakech',
    nameAr: 'Marrakech',
    nameFr: 'Marrakech',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '73',
    name: 'Tassoultante',
    nameAr: 'Tassoultante',
    nameFr: 'Tassoultante',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.5200, lng: -7.9500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '74',
    name: 'Saada',
    nameAr: 'Saada',
    nameFr: 'Saada',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.6000, lng: -8.0200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '75',
    name: 'Harbil',
    nameAr: 'Harbil',
    nameFr: 'Harbil',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.5800, lng: -8.0000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '76',
    name: 'Ait Ourir',
    nameAr: 'Ait Ourir',
    nameFr: 'Ait Ourir',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.5470, lng: -7.6670 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '77',
    name: 'Ourika',
    nameAr: 'Ourika',
    nameFr: 'Ourika',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.4000, lng: -7.8700 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '78',
    name: 'Kalaat Sraghna',
    nameAr: 'Kalaat Sraghna',
    nameFr: 'Kalaat Sraghna',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.0595, lng: -7.4067 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '79',
    name: 'Essaouira',
    nameAr: 'Essaouira',
    nameFr: 'Essaouira',
    region: 'Marrakech-Safi',
    coordinates: { lat: 31.5085, lng: -9.7595 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '80',
    name: 'Ben Guerir',
    nameAr: 'Ben Guerir',
    nameFr: 'Ben Guerir',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.2361, lng: -7.9533 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '81',
    name: 'Safi',
    nameAr: 'Safi',
    nameFr: 'Safi',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.2994, lng: -9.2372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '82',
    name: 'Youssoufia',
    nameAr: 'Youssoufia',
    nameFr: 'Youssoufia',
    region: 'Marrakech-Safi',
    coordinates: { lat: 32.2546, lng: -8.5280 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Drâa-Tafilalet
  {
    id: '83',
    name: 'Errachidia',
    nameAr: 'Errachidia',
    nameFr: 'Errachidia',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 31.9314, lng: -4.4283 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '84',
    name: 'Ouarzazate',
    nameAr: 'Ouarzazate',
    nameFr: 'Ouarzazate',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 30.9335, lng: -6.9370 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '85',
    name: 'Midelt',
    nameAr: 'Midelt',
    nameFr: 'Midelt',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 32.6852, lng: -4.7351 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '86',
    name: 'Zagora',
    nameAr: 'Zagora',
    nameFr: 'Zagora',
    region: 'Drâa-Tafilalet',
    coordinates: { lat: 30.3314, lng: -5.8372 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Souss-Massa
  {
    id: '87',
    name: 'Agadir',
    nameAr: 'Agadir',
    nameFr: 'Agadir',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4278, lng: -9.5981 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '88',
    name: 'Drargua',
    nameAr: 'Drargua',
    nameFr: 'Drargua',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4500, lng: -9.5500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '89',
    name: 'Inezgane',
    nameAr: 'Inezgane',
    nameFr: 'Inezgane',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3552, lng: -9.5369 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '90',
    name: 'Ait Melloul',
    nameAr: 'Ait Melloul',
    nameFr: 'Ait Melloul',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3400, lng: -9.4900 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '91',
    name: 'Dcheira El Jihadia',
    nameAr: 'Dcheira El Jihadia',
    nameFr: 'Dcheira El Jihadia',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3600, lng: -9.5200 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '92',
    name: 'Lqliaa',
    nameAr: 'Lqliaa',
    nameFr: 'Lqliaa',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3800, lng: -9.5500 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '93',
    name: 'Temsia',
    nameAr: 'Temsia',
    nameFr: 'Temsia',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4000, lng: -9.5800 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '94',
    name: 'Biougra',
    nameAr: 'Biougra',
    nameFr: 'Biougra',
    region: 'Souss-Massa',
    coordinates: { lat: 30.2348, lng: -9.3569 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '95',
    name: 'Ait Amira',
    nameAr: 'Ait Amira',
    nameFr: 'Ait Amira',
    region: 'Souss-Massa',
    coordinates: { lat: 30.2000, lng: -9.3000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '96',
    name: 'Sidi Bibi',
    nameAr: 'Sidi Bibi',
    nameFr: 'Sidi Bibi',
    region: 'Souss-Massa',
    coordinates: { lat: 30.6020, lng: -9.1720 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '97',
    name: 'Ouad Essafa',
    nameAr: 'Ouad Essafa',
    nameFr: 'Ouad Essafa',
    region: 'Souss-Massa',
    coordinates: { lat: 30.5500, lng: -9.2000 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '98',
    name: 'Taroudannt',
    nameAr: 'Taroudannt',
    nameFr: 'Taroudannt',
    region: 'Souss-Massa',
    coordinates: { lat: 30.4702, lng: -8.8777 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '99',
    name: 'Oulad Teima',
    nameAr: 'Oulad Teima',
    nameFr: 'Oulad Teima',
    region: 'Souss-Massa',
    coordinates: { lat: 30.3900, lng: -9.2100 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '100',
    name: 'Tiznit',
    nameAr: 'Tiznit',
    nameFr: 'Tiznit',
    region: 'Souss-Massa',
    coordinates: { lat: 29.6980, lng: -9.7320 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Guelmim-Oued Noun
  {
    id: '101',
    name: 'Guelmim',
    nameAr: 'Guelmim',
    nameFr: 'Guelmim',
    region: 'Guelmim-Oued Noun',
    coordinates: { lat: 28.9870, lng: -10.0575 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '102',
    name: 'Tan-Tan',
    nameAr: 'Tan-Tan',
    nameFr: 'Tan-Tan',
    region: 'Guelmim-Oued Noun',
    coordinates: { lat: 28.4378, lng: -11.1031 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Laâyoune-Sakia El Hamra
  {
    id: '103',
    name: 'Laâyoune',
    nameAr: 'Laâyoune',
    nameFr: 'Laâyoune',
    region: 'Laâyoune-Sakia El Hamra',
    coordinates: { lat: 27.1536, lng: -13.2033 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Dakhla-Oued Ed-Dahab
  {
    id: '104',
    name: 'Dakhla',
    nameAr: 'Dakhla',
    nameFr: 'Dakhla',
    region: 'Dakhla-Oued Ed-Dahab',
    coordinates: { lat: 23.7185, lng: -15.9582 },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Markets - Representative markets and souks across Moroccan cities
export const mockMarkets: Market[] = [
  // Tangier Markets
  {
    id: '1',
    cityId: '1',
    name: 'Grand Socco Market',
    nameAr: 'Grand Socco Market',
    nameFr: 'Grand Socco Market',
    address: 'Place du Grand Socco, Tangier',
    coordinates: { lat: 35.7595, lng: -5.8340 },
    openingHours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    cityId: '1',
    name: 'Souk Barra Tangier',
    nameAr: 'Souk Barra Tangier',
    nameFr: 'Souk Barra Tangier',
    address: 'Rue de Fes, Tangier',
    coordinates: { lat: 35.7555, lng: -5.8350 },
    openingHours: {
      monday: { open: '06:30', close: '18:30' },
      tuesday: { open: '06:30', close: '18:30' },
      wednesday: { open: '06:30', close: '18:30' },
      thursday: { open: '06:30', close: '18:30' },
      friday: { open: '06:30', close: '18:30' },
      saturday: { open: '06:30', close: '18:30' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Oujda Markets
  {
    id: '3',
    cityId: '11',
    name: 'Souk El Had Oujda',
    nameAr: 'Souk El Had Oujda',
    nameFr: 'Souk El Had Oujda',
    address: 'Boulevard Hassan II, Oujda',
    coordinates: { lat: 34.6814, lng: -1.9086 },
    openingHours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '18:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '07:00', close: '18:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Fez Markets
  {
    id: '4',
    cityId: '17',
    name: 'Souk El Attarine Fez',
    nameAr: 'Souk El Attarine Fez',
    nameFr: 'Souk El Attarine Fez',
    address: 'Medina, Fez',
    coordinates: { lat: 34.0181, lng: -5.0078 },
    openingHours: {
      monday: { open: '08:00', close: '19:00' },
      tuesday: { open: '08:00', close: '19:00' },
      wednesday: { open: '08:00', close: '19:00' },
      thursday: { open: '08:00', close: '19:00' },
      friday: { open: '08:00', close: '19:00' },
      saturday: { open: '08:00', close: '19:00' },
      sunday: { open: '09:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    cityId: '17',
    name: 'Marché Central Fez',
    nameAr: 'Marché Central Fez',
    nameFr: 'Marché Central Fez',
    address: 'Avenue Hassan II, Fez',
    coordinates: { lat: 34.0201, lng: -5.0058 },
    openingHours: {
      monday: { open: '06:00', close: '18:00' },
      tuesday: { open: '06:00', close: '18:00' },
      wednesday: { open: '06:00', close: '18:00' },
      thursday: { open: '06:00', close: '18:00' },
      friday: { open: '06:00', close: '18:00' },
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Rabat Markets
  {
    id: '6',
    cityId: '26',
    name: 'Rabat Central Market',
    nameAr: 'Rabat Central Market',
    nameFr: 'Rabat Central Market',
    address: 'Avenue Mohammed V, Rabat',
    coordinates: { lat: 34.0209, lng: -6.8416 },
    openingHours: {
      monday: { open: '06:30', close: '18:30' },
      tuesday: { open: '06:30', close: '18:30' },
      wednesday: { open: '06:30', close: '18:30' },
      thursday: { open: '06:30', close: '18:30' },
      friday: { open: '06:30', close: '18:30' },
      saturday: { open: '06:30', close: '18:30' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '7',
    cityId: '26',
    name: 'Souk Es Sebt Rabat',
    nameAr: 'Souk Es Sebt Rabat',
    nameFr: 'Souk Es Sebt Rabat',
    address: 'Hay Riad, Rabat',
    coordinates: { lat: 34.0189, lng: -6.8436 },
    openingHours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Casablanca Markets
  {
    id: '8',
    cityId: '50',
    name: 'Central Market Casablanca',
    nameAr: 'Central Market Casablanca',
    nameFr: 'Central Market Casablanca',
    address: 'Boulevard Mohammed V, Casablanca',
    coordinates: { lat: 33.5731, lng: -7.5898 },
    openingHours: {
      monday: { open: '06:00', close: '18:00' },
      tuesday: { open: '06:00', close: '18:00' },
      wednesday: { open: '06:00', close: '18:00' },
      thursday: { open: '06:00', close: '18:00' },
      friday: { open: '06:00', close: '18:00' },
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '9',
    cityId: '50',
    name: 'Derb Ghallef Market',
    nameAr: 'Derb Ghallef Market',
    nameFr: 'Derb Ghallef Market',
    address: 'Derb Ghallef, Casablanca',
    coordinates: { lat: 33.5650, lng: -7.6114 },
    openingHours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '10',
    cityId: '50',
    name: 'Hay Mohammadi Market',
    nameAr: 'Hay Mohammadi Market',
    nameFr: 'Hay Mohammadi Market',
    address: 'Hay Mohammadi, Casablanca',
    coordinates: { lat: 33.5500, lng: -7.6200 },
    openingHours: {
      monday: { open: '06:30', close: '18:30' },
      tuesday: { open: '06:30', close: '18:30' },
      wednesday: { open: '06:30', close: '18:30' },
      thursday: { open: '06:30', close: '18:30' },
      friday: { open: '06:30', close: '18:30' },
      saturday: { open: '06:30', close: '18:30' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Marrakech Markets
  {
    id: '11',
    cityId: '72',
    name: 'Jemaa el-Fnaa Market',
    nameAr: 'Jemaa el-Fnaa Market',
    nameFr: 'Jemaa el-Fnaa Market',
    address: 'Jemaa el-Fnaa, Marrakech',
    coordinates: { lat: 31.6295, lng: -7.9811 },
    openingHours: {
      monday: { open: '07:00', close: '20:00' },
      tuesday: { open: '07:00', close: '20:00' },
      wednesday: { open: '07:00', close: '20:00' },
      thursday: { open: '07:00', close: '20:00' },
      friday: { open: '07:00', close: '20:00' },
      saturday: { open: '07:00', close: '20:00' },
      sunday: { open: '07:00', close: '20:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '12',
    cityId: '72',
    name: 'Souk El Khemis Marrakech',
    nameAr: 'Souk El Khemis Marrakech',
    nameFr: 'Souk El Khemis Marrakech',
    address: 'Gueliz, Marrakech',
    coordinates: { lat: 31.6315, lng: -7.9831 },
    openingHours: {
      monday: { open: '06:00', close: '18:00' },
      tuesday: { open: '06:00', close: '18:00' },
      wednesday: { open: '06:00', close: '18:00' },
      thursday: { open: '06:00', close: '18:00' },
      friday: { open: '06:00', close: '18:00' },
      saturday: { open: '06:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Agadir Markets
  {
    id: '13',
    cityId: '87',
    name: 'Souk El Had Agadir',
    nameAr: 'Souk El Had Agadir',
    nameFr: 'Souk El Had Agadir',
    address: 'Boulevard Hassan II, Agadir',
    coordinates: { lat: 30.4278, lng: -9.5981 },
    openingHours: {
      monday: { open: '08:00', close: '18:00' },
      tuesday: { open: '08:00', close: '18:00' },
      wednesday: { open: '08:00', close: '18:00' },
      thursday: { open: '08:00', close: '18:00' },
      friday: { open: '08:00', close: '18:00' },
      saturday: { open: '08:00', close: '18:00' },
      sunday: { open: '08:00', close: '18:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Essaouira Markets
  {
    id: '14',
    cityId: '79',
    name: 'Souk Jdid Essaouira',
    nameAr: 'Souk Jdid Essaouira',
    nameFr: 'Souk Jdid Essaouira',
    address: 'Medina, Essaouira',
    coordinates: { lat: 31.5085, lng: -9.7595 },
    openingHours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Meknès Markets
  {
    id: '15',
    cityId: '19',
    name: 'Souk Bezaara Meknès',
    nameAr: 'Souk Bezaara Meknès',
    nameFr: 'Souk Bezaara Meknès',
    address: 'Ville Nouvelle, Meknès',
    coordinates: { lat: 33.8935, lng: -5.5473 },
    openingHours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '18:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Salé Markets
  {
    id: '16',
    cityId: '27',
    name: 'Souk El Ghezel Salé',
    nameAr: 'Souk El Ghezel Salé',
    nameFr: 'Souk El Ghezel Salé',
    address: 'Medina, Salé',
    coordinates: { lat: 34.0531, lng: -6.7985 },
    openingHours: {
      monday: { open: '07:00', close: '18:30' },
      tuesday: { open: '07:00', close: '18:30' },
      wednesday: { open: '07:00', close: '18:30' },
      thursday: { open: '07:00', close: '18:30' },
      friday: { open: '07:00', close: '18:30' },
      saturday: { open: '07:00', close: '18:30' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Ouarzazate Markets
  {
    id: '17',
    cityId: '84',
    name: 'Souk El Khemis Ouarzazate',
    nameAr: 'Souk El Khemis Ouarzazate',
    nameFr: 'Souk El Khemis Ouarzazate',
    address: 'Centre Ville, Ouarzazate',
    coordinates: { lat: 30.9335, lng: -6.9370 },
    openingHours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '18:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Nador Markets
  {
    id: '18',
    cityId: '12',
    name: 'Souk Tleta Nador',
    nameAr: 'Souk Tleta Nador',
    nameFr: 'Souk Tleta Nador',
    address: 'Centre Ville, Nador',
    coordinates: { lat: 35.1740, lng: -2.9287 },
    openingHours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '18:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Tetouan Markets
  {
    id: '19',
    cityId: '6',
    name: 'Souk El Fouki Tetouan',
    nameAr: 'Souk El Fouki Tetouan',
    nameFr: 'Souk El Fouki Tetouan',
    address: 'Medina, Tétouan',
    coordinates: { lat: 35.5785, lng: -5.3684 },
    openingHours: {
      monday: { open: '07:00', close: '19:00' },
      tuesday: { open: '07:00', close: '19:00' },
      wednesday: { open: '07:00', close: '19:00' },
      thursday: { open: '07:00', close: '19:00' },
      friday: { open: '07:00', close: '19:00' },
      saturday: { open: '07:00', close: '19:00' },
      sunday: { open: '08:00', close: '17:00' },
    },
    marketType: 'traditional',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },

  // Khouribga Markets
  {
    id: '20',
    cityId: '48',
    name: 'Souk Es Sebt Khouribga',
    nameAr: 'Souk Es Sebt Khouribga',
    nameFr: 'Souk Es Sebt Khouribga',
    address: 'Centre Ville, Khouribga',
    coordinates: { lat: 32.8811, lng: -6.9063 },
    openingHours: {
      monday: { open: '07:00', close: '18:00' },
      tuesday: { open: '07:00', close: '18:00' },
      wednesday: { open: '07:00', close: '18:00' },
      thursday: { open: '07:00', close: '18:00' },
      friday: { open: '07:00', close: '18:00' },
      saturday: { open: '07:00', close: '18:00' },
      sunday: { open: '08:00', close: '16:00' },
    },
    marketType: 'modern',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Products
export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Tomatoes',
    nameAr: 'Tomatoes',
    nameFr: 'Tomatoes',
    category: 'vegetables',
    unit: 'kg',
    commonUnits: ['kg', 'piece'],
    imageUrl: '/images/products/tomatoes.jpg',
    isSeasonal: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    name: 'Potatoes',
    nameAr: 'Potatoes',
    nameFr: 'Potatoes',
    category: 'vegetables',
    unit: 'kg',
    commonUnits: ['kg', 'piece'],
    imageUrl: '/images/products/potatoes.jpg',
    isSeasonal: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '3',
    name: 'Oranges',
    nameAr: 'Oranges',
    nameFr: 'Oranges',
    category: 'fruits',
    unit: 'kg',
    commonUnits: ['kg', 'piece', 'bundle'],
    imageUrl: '/images/products/oranges.jpg',
    isSeasonal: true,
    seasonStart: 11,
    seasonEnd: 4,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    name: 'Bananas',
    nameAr: 'Bananas',
    nameFr: 'Bananas',
    category: 'fruits',
    unit: 'kg',
    commonUnits: ['kg', 'bundle'],
    imageUrl: '/images/products/bananas.jpg',
    isSeasonal: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '5',
    name: 'Onions',
    nameAr: 'Onions',
    nameFr: 'Onions',
    category: 'vegetables',
    unit: 'kg',
    commonUnits: ['kg', 'piece'],
    imageUrl: '/images/products/onions.jpg',
    isSeasonal: false,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: '6',
    name: 'Carrots',
    nameAr: 'Carrots',
    nameFr: 'Carrots',
    category: 'vegetables',
    unit: 'kg',
    commonUnits: ['kg', 'bundle'],
    imageUrl: '/images/products/carrots.jpg',
    isSeasonal: false,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock Badges
export const mockBadges: Badge[] = [
  {
    id: '1',
    type: 'reliable_reporter',
    name: 'Reliable Reporter',
    nameAr: 'Reliable Reporter',
    nameFr: 'Reliable Reporter',
    description: 'Consistently accurate price submissions',
    icon: '🏆',
    earnedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    type: 'market_expert',
    name: 'Market Expert',
    nameAr: 'Market Expert',
    nameFr: 'Market Expert',
    description: 'Deep knowledge of market conditions',
    icon: '🎯',
    earnedAt: new Date('2024-02-01'),
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'ahmed4star@gmail.com',
    username: 'ahmed4star',
    fullName: 'Ahmed El Morocci',
    avatarUrl: '/images/avatars/ahmed.jpg',
    phone: '+212612345678',
    city: 'Casablanca',
    badges: [mockBadges[0]],
    reputationScore: 850,
    totalSubmissions: 127,
    accurateSubmissions: 118,
    isVerified: true,
    isAdmin: true,
    isBanned: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '2',
    email: 'fatima@example.com',
    username: 'fatima_rbat',
    fullName: 'Fatima Zahra',
    avatarUrl: '/images/avatars/fatima.jpg',
    phone: '+212623456789',
    city: 'Rabat',
    badges: [mockBadges[1]],
    reputationScore: 920,
    totalSubmissions: 89,
    accurateSubmissions: 85,
    isVerified: true,
    isAdmin: false,
    isBanned: false,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '3',
    email: 'admin@sooqprice.ma',
    username: 'admin',
    fullName: 'SooqPrice Admin',
    avatarUrl: '/images/avatars/admin.jpg',
    city: 'Rabat',
    badges: [],
    reputationScore: 0,
    totalSubmissions: 0,
    accurateSubmissions: 0,
    isVerified: true,
    isAdmin: true,
    isBanned: false,
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '4',
    email: 'youssef.fez@gmail.com',
    username: 'youssef_fez',
    fullName: 'Youssef Benali',
    avatarUrl: '/images/avatars/youssef.jpg',
    phone: '+212645123789',
    city: 'Fez',
    badges: [mockBadges[0]],
    reputationScore: 650,
    totalSubmissions: 45,
    accurateSubmissions: 42,
    isVerified: true,
    isAdmin: false,
    isBanned: false,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: '5',
    email: 'aicha.marrakech@gmail.com',
    username: 'aicha_mkch',
    fullName: 'Aicha Bennani',
    avatarUrl: '/images/avatars/aicha.jpg',
    phone: '+212667234567',
    city: 'Marrakech',
    badges: [mockBadges[1]],
    reputationScore: 720,
    totalSubmissions: 67,
    accurateSubmissions: 61,
    isVerified: true,
    isAdmin: false,
    isBanned: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-06-01'),
  },
];

// Mock Price Submissions
export const mockPriceSubmissions: PriceSubmission[] = [
  {
    id: '1',
    userId: '1',
    marketId: '8', // Central Market Casablanca
    productId: '1',
    price: 8.5,
    unit: 'kg',
    quality: 'good',
    notes: 'Fresh tomatoes, good quality',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-10'),
    submissionDate: new Date('2024-06-10'),
    createdAt: new Date('2024-06-10'),
    user: mockUsers[0],
    market: mockMarkets[7], // Central Market Casablanca
    product: mockProducts[0],
  },
  {
    id: '2',
    userId: '2',
    marketId: '9', // Derb Ghallef Market
    productId: '1',
    price: 9.0,
    unit: 'kg',
    quality: 'excellent',
    notes: 'Premium quality tomatoes',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-10'),
    submissionDate: new Date('2024-06-10'),
    createdAt: new Date('2024-06-10'),
    user: mockUsers[1],
    market: mockMarkets[8], // Derb Ghallef Market
    product: mockProducts[0],
  },
  {
    id: '3',
    userId: '1',
    marketId: '8', // Central Market Casablanca
    productId: '2',
    price: 4.5,
    unit: 'kg',
    quality: 'good',
    notes: 'Regular potatoes',
    verificationStatus: 'pending',
    submissionDate: new Date('2024-06-11'),
    createdAt: new Date('2024-06-11'),
    user: mockUsers[0],
    market: mockMarkets[7], // Central Market Casablanca
    product: mockProducts[1],
  },
  {
    id: '4',
    userId: '2',
    marketId: '6', // Rabat Central Market
    productId: '3',
    price: 12.0,
    unit: 'kg',
    quality: 'excellent',
    notes: 'Sweet oranges, perfect for juice',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-09'),
    submissionDate: new Date('2024-06-09'),
    createdAt: new Date('2024-06-09'),
    user: mockUsers[1],
    market: mockMarkets[5], // Rabat Central Market
    product: mockProducts[2],
  },
  {
    id: '5',
    userId: '1',
    marketId: '9', // Derb Ghallef Market
    productId: '4',
    price: 15.0,
    unit: 'kg',
    quality: 'good',
    notes: 'Imported bananas',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-08'),
    submissionDate: new Date('2024-06-08'),
    createdAt: new Date('2024-06-08'),
    user: mockUsers[0],
    market: mockMarkets[8], // Derb Ghallef Market
    product: mockProducts[3],
  },
  {
    id: '6',
    userId: '2',
    marketId: '11', // Jemaa el-Fnaa Market Marrakech
    productId: '1',
    price: 7.5,
    unit: 'kg',
    quality: 'good',
    notes: 'Local tomatoes from the souk',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-12'),
    submissionDate: new Date('2024-06-12'),
    createdAt: new Date('2024-06-12'),
    user: mockUsers[1],
    market: mockMarkets[10], // Jemaa el-Fnaa Market
    product: mockProducts[0],
  },
  {
    id: '7',
    userId: '1',
    marketId: '4', // Souk El Attarine Fez
    productId: '5',
    price: 6.0,
    unit: 'kg',
    quality: 'excellent',
    notes: 'Fresh onions from Fez medina',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-11'),
    submissionDate: new Date('2024-06-11'),
    createdAt: new Date('2024-06-11'),
    user: mockUsers[0],
    market: mockMarkets[3], // Souk El Attarine Fez
    product: mockProducts[4],
  },
  {
    id: '8',
    userId: '2',
    marketId: '13', // Souk El Had Agadir
    productId: '6',
    price: 5.5,
    unit: 'kg',
    quality: 'good',
    notes: 'Carrots from Souss valley',
    verificationStatus: 'pending',
    submissionDate: new Date('2024-06-13'),
    createdAt: new Date('2024-06-13'),
    user: mockUsers[1],
    market: mockMarkets[12], // Souk El Had Agadir
    product: mockProducts[5],
  },
  {
    id: '9',
    userId: '1',
    marketId: '1', // Grand Socco Market Tangier
    productId: '3',
    price: 13.0,
    unit: 'kg',
    quality: 'excellent',
    notes: 'Fresh oranges from the north',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-12'),
    submissionDate: new Date('2024-06-12'),
    createdAt: new Date('2024-06-12'),
    user: mockUsers[0],
    market: mockMarkets[0], // Grand Socco Market
    product: mockProducts[2],
  },
  {
    id: '10',
    userId: '2',
    marketId: '14', // Souk Jdid Essaouira
    productId: '4',
    price: 16.0,
    unit: 'kg',
    quality: 'good',
    notes: 'Bananas from coastal market',
    verificationStatus: 'verified',
    verifiedBy: '3',
    verifiedAt: new Date('2024-06-10'),
    submissionDate: new Date('2024-06-10'),
    createdAt: new Date('2024-06-10'),
    user: mockUsers[1],
    market: mockMarkets[13], // Souk Jdid Essaouira
    product: mockProducts[3],
  },
];

// Helper functions for mock data
export const getMockCityById = (id: string): City | undefined => 
  mockCities.find(city => city.id === id);

export const getMockMarketById = (id: string): Market | undefined => 
  mockMarkets.find(market => market.id === id);

// Get product by id
export const getMockProductById = (productId: string): Product | undefined => {
  return mockProducts.find(product => product.id === productId);
};

export const getMockUserById = (id: string): User | undefined => 
  mockUsers.find(user => user.id === id);

export const getMockMarketsByCity = (cityId: string): Market[] => 
  mockMarkets.filter(market => market.cityId === cityId);

export const getMockSubmissionsByMarket = (marketId: string): PriceSubmission[] => 
  mockPriceSubmissions.filter(submission => submission.marketId === marketId);

export const getMockSubmissionsByProduct = (productId: string): PriceSubmission[] => 
  mockPriceSubmissions.filter(submission => submission.productId === productId);

export const getMockSubmissionsByUser = (userId: string): PriceSubmission[] => 
  mockPriceSubmissions.filter(submission => submission.userId === userId);

// Get submissions by city
export const getMockSubmissionsByCity = (cityId: string): PriceSubmission[] => {
  const cityMarkets = getMockMarketsByCity(cityId);
  const marketIds = cityMarkets.map(m => m.id);
  return mockPriceSubmissions.filter(submission => 
    marketIds.includes(submission.marketId)
  );
};

// Search function for products
export const searchMockProducts = (query: string): Product[] => {
  const lowerQuery = query.toLowerCase();
  return mockProducts.filter(product => 
    product.name.toLowerCase().includes(lowerQuery) ||
    product.nameAr.toLowerCase().includes(lowerQuery) ||
    product.nameFr.toLowerCase().includes(lowerQuery)
  );
};

// Get latest prices for a product across markets
export const getMockLatestPrices = (productId: string): PriceSubmission[] => {
  const submissions = getMockSubmissionsByProduct(productId);
  const latestByMarket = new Map<string, PriceSubmission>();
  
  submissions.forEach(submission => {
    const existing = latestByMarket.get(submission.marketId);
    if (!existing || submission.submissionDate > existing.submissionDate) {
      latestByMarket.set(submission.marketId, submission);
    }
  });
  
  return Array.from(latestByMarket.values());
};
